# Generated by Django 4.2 on 2023-04-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivente',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
