# Generated by Django 4.2 on 2023-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivente',
            name='items',
            field=models.ManyToManyField(blank=True, to='sobreviventes.item'),
        ),
    ]
